services:
  clone-tabnews-database:
    container_name: "clone-tabnews-database"
    image: "postgres:16.0-alpine3.18"
    env_file:
      - "../.env.development"
    ports:
      - "5433:5432"
  mailcatcher:
    container_name: "mailcatcher-dev"
    image: "sj26/mailcatcher"
    ports:
      - "1025:1025"
      - "1080:1080"
